var save;
save = ini_open("omegadata.sav");
ini_write_string("Data", "name", global.myname);
ini_write_string("Data", "ip", global.myipaddress);
ini_write_real("Data", "shipselect", global.shipselect);
ini_write_real("Data", "primary", global.primary);
ini_write_real("Data", "secondary1", global.secondary[1]);
ini_write_real("Data", "secondary2", global.secondary[2]);
ini_write_real("Data", "secondary3", global.secondary[3]);
ini_write_real("Data", "secondary4", global.secondary[4]);
ini_write_real("Data", "playerkills", global.playerkills);
ini_write_real("Data", "playerdeaths", global.playerdeaths);
ini_write_real("Data", "playermatchwin", global.playermatchwin);
ini_write_real("Data", "playermatchloss", global.playermatchloss);
ini_write_real("Data", "playerduelwin", global.playerduelwin);
ini_write_real("Data", "playerduelloss", global.playerduelloss);
ini_write_real("Data", "playerdodge", global.playerdodge);
ini_write_real("Data", "musictoggle", global.musictoggle);
ini_write_real("Data", "sfxtoggle", global.sfxtoggle);
ini_write_real("Data", "firingmode", global.firingmode);
ini_close();
